# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.platform_cal_provider_api import PlatformCalProviderApi


class TestPlatformCalProviderApi(unittest.TestCase):
    """PlatformCalProviderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlatformCalProviderApi()

    def tearDown(self) -> None:
        pass

    def test_cal_provider_controller_verify_access_token(self) -> None:
        """Test case for cal_provider_controller_verify_access_token

        Verify an access token
        """
        pass

    def test_cal_provider_controller_verify_client_id(self) -> None:
        """Test case for cal_provider_controller_verify_client_id

        Get a provider
        """
        pass


if __name__ == '__main__':
    unittest.main()
