# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.event_type_output20240614_booking_window_inner import EventTypeOutput20240614BookingWindowInner

class TestEventTypeOutput20240614BookingWindowInner(unittest.TestCase):
    """EventTypeOutput20240614BookingWindowInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventTypeOutput20240614BookingWindowInner:
        """Test EventTypeOutput20240614BookingWindowInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventTypeOutput20240614BookingWindowInner`
        """
        model = EventTypeOutput20240614BookingWindowInner()
        if include_optional:
            return EventTypeOutput20240614BookingWindowInner(
                type = 'businessDays',
                value = [2030-09-05, 2030-09-09],
                rolling = True
            )
        else:
            return EventTypeOutput20240614BookingWindowInner(
                type = 'businessDays',
                value = [2030-09-05, 2030-09-09],
        )
        """

    def testEventTypeOutput20240614BookingWindowInner(self):
        """Test EventTypeOutput20240614BookingWindowInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
