# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.calendars_api import CalendarsApi


class TestCalendarsApi(unittest.TestCase):
    """CalendarsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CalendarsApi()

    def tearDown(self) -> None:
        pass

    def test_calendars_controller_check(self) -> None:
        """Test case for calendars_controller_check

        Check a calendar connection
        """
        pass

    def test_calendars_controller_check_ics_feed(self) -> None:
        """Test case for calendars_controller_check_ics_feed

        Check an ICS feed
        """
        pass

    def test_calendars_controller_create_ics_feed(self) -> None:
        """Test case for calendars_controller_create_ics_feed

        Save an ICS feed
        """
        pass

    def test_calendars_controller_delete_calendar_credentials(self) -> None:
        """Test case for calendars_controller_delete_calendar_credentials

        Disconnect a calendar
        """
        pass

    def test_calendars_controller_get_busy_times(self) -> None:
        """Test case for calendars_controller_get_busy_times

        Get busy times
        """
        pass

    def test_calendars_controller_get_calendars(self) -> None:
        """Test case for calendars_controller_get_calendars

        Get all calendars
        """
        pass

    def test_calendars_controller_redirect(self) -> None:
        """Test case for calendars_controller_redirect

        Get connect URL
        """
        pass

    def test_calendars_controller_save(self) -> None:
        """Test case for calendars_controller_save

        Save a calendar
        """
        pass

    def test_calendars_controller_sync_credentials(self) -> None:
        """Test case for calendars_controller_sync_credentials

        Sync credentials
        """
        pass


if __name__ == '__main__':
    unittest.main()
