# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_event_type_input20240614_booking_limits_duration import CreateEventTypeInput20240614BookingLimitsDuration

class TestCreateEventTypeInput20240614BookingLimitsDuration(unittest.TestCase):
    """CreateEventTypeInput20240614BookingLimitsDuration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEventTypeInput20240614BookingLimitsDuration:
        """Test CreateEventTypeInput20240614BookingLimitsDuration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEventTypeInput20240614BookingLimitsDuration`
        """
        model = CreateEventTypeInput20240614BookingLimitsDuration()
        if include_optional:
            return CreateEventTypeInput20240614BookingLimitsDuration(
                day = 60,
                week = 120,
                month = 180,
                year = 240,
                disabled = True
            )
        else:
            return CreateEventTypeInput20240614BookingLimitsDuration(
                disabled = True,
        )
        """

    def testCreateEventTypeInput20240614BookingLimitsDuration(self):
        """Test CreateEventTypeInput20240614BookingLimitsDuration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
