# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_bookings_output20240813 import GetBookingsOutput20240813

class TestGetBookingsOutput20240813(unittest.TestCase):
    """GetBookingsOutput20240813 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBookingsOutput20240813:
        """Test GetBookingsOutput20240813
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBookingsOutput20240813`
        """
        model = GetBookingsOutput20240813()
        if include_optional:
            return GetBookingsOutput20240813(
                status = 'success',
                data = [
                    null
                    ],
                error = None
            )
        else:
            return GetBookingsOutput20240813(
                status = 'success',
                data = [
                    null
                    ],
        )
        """

    def testGetBookingsOutput20240813(self):
        """Test GetBookingsOutput20240813"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
