# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_event_type_input20240614_locations_inner import CreateEventTypeInput20240614LocationsInner

class TestCreateEventTypeInput20240614LocationsInner(unittest.TestCase):
    """CreateEventTypeInput20240614LocationsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEventTypeInput20240614LocationsInner:
        """Test CreateEventTypeInput20240614LocationsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEventTypeInput20240614LocationsInner`
        """
        model = CreateEventTypeInput20240614LocationsInner()
        if include_optional:
            return CreateEventTypeInput20240614LocationsInner(
                type = 'phone',
                address = '123 Example St, City, Country',
                public = True,
                link = 'https://customvideo.com/join/123456',
                integration = 'cal-video',
                phone = '+37120993151'
            )
        else:
            return CreateEventTypeInput20240614LocationsInner(
                type = 'phone',
                address = '123 Example St, City, Country',
                public = True,
                link = 'https://customvideo.com/join/123456',
                integration = 'cal-video',
                phone = '+37120993151',
        )
        """

    def testCreateEventTypeInput20240614LocationsInner(self):
        """Test CreateEventTypeInput20240614LocationsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
