# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.selected_calendars_api import SelectedCalendarsApi


class TestSelectedCalendarsApi(unittest.TestCase):
    """SelectedCalendarsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SelectedCalendarsApi()

    def tearDown(self) -> None:
        pass

    def test_selected_calendars_controller_add_selected_calendar(self) -> None:
        """Test case for selected_calendars_controller_add_selected_calendar

        Add a selected calendar
        """
        pass

    def test_selected_calendars_controller_remove_selected_calendar(self) -> None:
        """Test case for selected_calendars_controller_remove_selected_calendar

        Delete a selected calendar
        """
        pass


if __name__ == '__main__':
    unittest.main()
