# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.managed_user_output import ManagedUserOutput

class TestManagedUserOutput(unittest.TestCase):
    """ManagedUserOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagedUserOutput:
        """Test ManagedUserOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManagedUserOutput`
        """
        model = ManagedUserOutput()
        if include_optional:
            return ManagedUserOutput(
                id = 1,
                email = 'alice+cluo37fwd0001khkzqqynkpj3@example.com',
                username = 'alice',
                name = 'alice',
                time_zone = 'America/New_York',
                week_start = 'Sunday',
                created_date = '2024-04-01T00:00:00.000Z',
                time_format = 12,
                default_schedule_id = 1.337,
                locale = 'en'
            )
        else:
            return ManagedUserOutput(
                id = 1,
                email = 'alice+cluo37fwd0001khkzqqynkpj3@example.com',
                username = 'alice',
                name = 'alice',
                time_zone = 'America/New_York',
                week_start = 'Sunday',
                created_date = '2024-04-01T00:00:00.000Z',
                time_format = 12,
                default_schedule_id = 1.337,
        )
        """

    def testManagedUserOutput(self):
        """Test ManagedUserOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
