# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.o_auth_api import OAuthApi


class TestOAuthApi(unittest.TestCase):
    """OAuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OAuthApi()

    def tearDown(self) -> None:
        pass

    def test_o_auth_flow_controller_authorize(self) -> None:
        """Test case for o_auth_flow_controller_authorize

        Authorize an OAuth client
        """
        pass

    def test_o_auth_flow_controller_exchange(self) -> None:
        """Test case for o_auth_flow_controller_exchange

        Exchange authorization code for access tokens
        """
        pass

    def test_o_auth_flow_controller_refresh_access_token(self) -> None:
        """Test case for o_auth_flow_controller_refresh_access_token

        """
        pass


if __name__ == '__main__':
    unittest.main()
