# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.delete_calendar_credentials_input_body_dto import DeleteCalendarCredentialsInputBodyDto

class TestDeleteCalendarCredentialsInputBodyDto(unittest.TestCase):
    """DeleteCalendarCredentialsInputBodyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteCalendarCredentialsInputBodyDto:
        """Test DeleteCalendarCredentialsInputBodyDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteCalendarCredentialsInputBodyDto`
        """
        model = DeleteCalendarCredentialsInputBodyDto()
        if include_optional:
            return DeleteCalendarCredentialsInputBodyDto(
                id = 10
            )
        else:
            return DeleteCalendarCredentialsInputBodyDto(
                id = 10,
        )
        """

    def testDeleteCalendarCredentialsInputBodyDto(self):
        """Test DeleteCalendarCredentialsInputBodyDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
