# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.me_api import MeApi


class TestMeApi(unittest.TestCase):
    """MeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MeApi()

    def tearDown(self) -> None:
        pass

    def test_me_controller_get_me(self) -> None:
        """Test case for me_controller_get_me

        Get my profile
        """
        pass

    def test_me_controller_update_me(self) -> None:
        """Test case for me_controller_update_me

        Update my profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
