# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_recurring_booking_input20240813 import CreateRecurringBookingInput20240813

class TestCreateRecurringBookingInput20240813(unittest.TestCase):
    """CreateRecurringBookingInput20240813 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateRecurringBookingInput20240813:
        """Test CreateRecurringBookingInput20240813
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateRecurringBookingInput20240813`
        """
        model = CreateRecurringBookingInput20240813()
        if include_optional:
            return CreateRecurringBookingInput20240813(
                start = '2024-08-13T09:00:00Z',
                event_type_id = 123,
                attendee = openapi_client.models.attendee.Attendee(
                    name = 'John Doe', 
                    email = 'john.doe@example.com', 
                    time_zone = 'America/New_York', 
                    language = 'en', ),
                guests = ["guest1@example.com","guest2@example.com"],
                location = 'https://example.com/meeting',
                booking_fields_responses = {"customField":"customValue"}
            )
        else:
            return CreateRecurringBookingInput20240813(
                start = '2024-08-13T09:00:00Z',
                event_type_id = 123,
                attendee = openapi_client.models.attendee.Attendee(
                    name = 'John Doe', 
                    email = 'john.doe@example.com', 
                    time_zone = 'America/New_York', 
                    language = 'en', ),
        )
        """

    def testCreateRecurringBookingInput20240813(self):
        """Test CreateRecurringBookingInput20240813"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
