# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_event_type_input20240614_recurrence import CreateEventTypeInput20240614Recurrence

class TestCreateEventTypeInput20240614Recurrence(unittest.TestCase):
    """CreateEventTypeInput20240614Recurrence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateEventTypeInput20240614Recurrence:
        """Test CreateEventTypeInput20240614Recurrence
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateEventTypeInput20240614Recurrence`
        """
        model = CreateEventTypeInput20240614Recurrence()
        if include_optional:
            return CreateEventTypeInput20240614Recurrence(
                interval = 10,
                occurrences = 10,
                frequency = 'yearly',
                disabled = True
            )
        else:
            return CreateEventTypeInput20240614Recurrence(
                interval = 10,
                occurrences = 10,
                frequency = 'yearly',
                disabled = True,
        )
        """

    def testCreateEventTypeInput20240614Recurrence(self):
        """Test CreateEventTypeInput20240614Recurrence"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
