# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_organization_user_input import CreateOrganizationUserInput

class TestCreateOrganizationUserInput(unittest.TestCase):
    """CreateOrganizationUserInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrganizationUserInput:
        """Test CreateOrganizationUserInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrganizationUserInput`
        """
        model = CreateOrganizationUserInput()
        if include_optional:
            return CreateOrganizationUserInput(
                email = 'user@example.com',
                username = 'user123',
                weekday = 'Monday',
                brand_color = '#FFFFFF',
                dark_brand_color = '#000000',
                hide_branding = False,
                time_zone = 'America/New_York',
                theme = 'dark',
                app_theme = 'light',
                time_format = 24,
                default_schedule_id = 1,
                locale = 'en',
                avatar_url = 'https://example.com/avatar.jpg',
                organization_role = None,
                auto_accept = None
            )
        else:
            return CreateOrganizationUserInput(
                email = 'user@example.com',
                organization_role = None,
                auto_accept = None,
        )
        """

    def testCreateOrganizationUserInput(self):
        """Test CreateOrganizationUserInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
