# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.seats20240614 import Seats20240614

class TestSeats20240614(unittest.TestCase):
    """Seats20240614 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Seats20240614:
        """Test Seats20240614
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Seats20240614`
        """
        model = Seats20240614()
        if include_optional:
            return Seats20240614(
                seats_per_time_slot = 4,
                show_attendee_info = True,
                show_availability_count = True
            )
        else:
            return Seats20240614(
                seats_per_time_slot = 4,
                show_attendee_info = True,
                show_availability_count = True,
        )
        """

    def testSeats20240614(self):
        """Test Seats20240614"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
