# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.provider_verify_client_output import ProviderVerifyClientOutput

class TestProviderVerifyClientOutput(unittest.TestCase):
    """ProviderVerifyClientOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderVerifyClientOutput:
        """Test ProviderVerifyClientOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProviderVerifyClientOutput`
        """
        model = ProviderVerifyClientOutput()
        if include_optional:
            return ProviderVerifyClientOutput(
                status = 'success',
                data = openapi_client.models.provider_verify_client_data.ProviderVerifyClientData(
                    client_id = '', 
                    organization_id = 1.337, 
                    name = '', )
            )
        else:
            return ProviderVerifyClientOutput(
                status = 'success',
                data = openapi_client.models.provider_verify_client_data.ProviderVerifyClientData(
                    client_id = '', 
                    organization_id = 1.337, 
                    name = '', ),
        )
        """

    def testProviderVerifyClientOutput(self):
        """Test ProviderVerifyClientOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
