# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.me_org_output import MeOrgOutput
from typing import Optional, Set
from typing_extensions import Self

class MeOutput(BaseModel):
    """
    MeOutput
    """ # noqa: E501
    id: Union[StrictFloat, StrictInt]
    username: StrictStr
    email: StrictStr
    time_format: Union[StrictFloat, StrictInt] = Field(alias="timeFormat")
    default_schedule_id: Optional[Union[StrictFloat, StrictInt]] = Field(alias="defaultScheduleId")
    week_start: StrictStr = Field(alias="weekStart")
    time_zone: StrictStr = Field(alias="timeZone")
    organization_id: Optional[Union[StrictFloat, StrictInt]] = Field(alias="organizationId")
    organization: Optional[MeOrgOutput] = None
    __properties: ClassVar[List[str]] = ["id", "username", "email", "timeFormat", "defaultScheduleId", "weekStart", "timeZone", "organizationId", "organization"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organization
        if self.organization:
            _dict['organization'] = self.organization.to_dict()
        # set to None if default_schedule_id (nullable) is None
        # and model_fields_set contains the field
        if self.default_schedule_id is None and "default_schedule_id" in self.model_fields_set:
            _dict['defaultScheduleId'] = None

        # set to None if organization_id (nullable) is None
        # and model_fields_set contains the field
        if self.organization_id is None and "organization_id" in self.model_fields_set:
            _dict['organizationId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "username": obj.get("username"),
            "email": obj.get("email"),
            "timeFormat": obj.get("timeFormat"),
            "defaultScheduleId": obj.get("defaultScheduleId"),
            "weekStart": obj.get("weekStart"),
            "timeZone": obj.get("timeZone"),
            "organizationId": obj.get("organizationId"),
            "organization": MeOrgOutput.from_dict(obj["organization"]) if obj.get("organization") is not None else None
        })
        return _obj


