# coding: utf-8

"""
    Cal.com API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ReserveSlotInput(BaseModel):
    """
    ReserveSlotInput
    """ # noqa: E501
    event_type_id: Union[StrictFloat, StrictInt] = Field(description="Event Type ID for which timeslot is being reserved.", alias="eventTypeId")
    slot_utc_start_date: StrictStr = Field(description="Start date of the slot in UTC timezone.", alias="slotUtcStartDate")
    slot_utc_end_date: StrictStr = Field(description="End date of the slot in UTC timezone.", alias="slotUtcEndDate")
    booking_uid: Optional[StrictStr] = Field(default=None, description="Optional but only for events with seats. Used to retrieve booking of a seated event.", alias="bookingUid")
    __properties: ClassVar[List[str]] = ["eventTypeId", "slotUtcStartDate", "slotUtcEndDate", "bookingUid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReserveSlotInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReserveSlotInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eventTypeId": obj.get("eventTypeId"),
            "slotUtcStartDate": obj.get("slotUtcStartDate"),
            "slotUtcEndDate": obj.get("slotUtcEndDate"),
            "bookingUid": obj.get("bookingUid")
        })
        return _obj


